name: second_workflow
on: push

jobs:
    run-first-command:
        runs-on: ubuntu-latest
        steps:
            - name: Display Node Version
              run: echo "Some Text"
            - name: Command in Multiline
              run: |
               node -v
    run-parallel-command:
        runs-on: windows-latest       
        steps:
            - name: Display Node Version on Windows
              run: node -v
    run-second-command:
        runs-on: macos-latest
        needs: run-first-command      
        steps:
            - name: Display Node Version on MacOs
              run: node -v
